# Generated by Django 5.2.7 on 2025-11-06 12:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Profile', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HRRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SELECTED', 'Selected'), ('REJECTED', 'Rejected')], default='PENDING', max_length=10)),
                ('remarks', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(auto_now=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Requests', to='Profile.newjoineprofile')),
                ('hr_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Requests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
