# Generated by Django 5.2.7 on 2025-11-21 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Requests', '0002_alter_hrrequest_hr_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hrrequest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=10),
        ),
    ]
