# Generated by Django 5.2.7 on 2025-12-08 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Project', models.CharField(blank=True, max_length=255, null=True)),
                ('task', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('Things_To_Notice', models.TextField(blank=True, null=True)),
                ('Deadline', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HrUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taskUpdate', models.TextField(blank=True, null=True)),
                ('NewRule', models.CharField(blank=True, max_length=255, null=True)),
                ('Notice', models.TextField(blank=True, null=True)),
                ('Celebration', models.TextField(blank=True, null=True)),
                ('Preparation', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='InternUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Project', models.CharField(blank=True, max_length=255, null=True)),
                ('LearnToday', models.CharField(blank=True, max_length=255, null=True)),
                ('Source', models.CharField(blank=True, max_length=255, null=True)),
                ('WorkWith', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='NewjoineUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Announcement', models.CharField(blank=True, max_length=255, null=True)),
                ('FieldToDecide', models.TextField(blank=True, null=True)),
                ('BePreparedFor', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
