# Generated by Django 5.2.7 on 2025-11-08 13:03

import django.contrib.postgres.fields
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.CharField(max_length=60, unique=True, verbose_name='Email Address')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=18)),
                ('role', models.CharField(choices=[('NJ', 'NewJoine'), ('Int', 'Intern'), ('Emp', 'Employee'), ('HR', 'HR'), ('MG', 'Manager'), ('OWN', 'Owner')], max_length=20)),
                ('technology', models.CharField(blank=True, choices=[('BD', 'backend'), ('FD', 'frontend'), ('FS', 'fullstack')], verbose_name='Technology')),
                ('Experience', models.CharField(choices=[('1Y', '1 Years'), ('2Y', '2 Years'), ('3Y', '3 Years'), ('4Y', '4 Years'), ('5Y', '5 Years'), ('6Y', '6 Years'), ('7Y+', '7 Years')], default='1Y', verbose_name='Experience')),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_NewJoine', models.BooleanField(default=False)),
                ('is_Intern', models.BooleanField(default=False)),
                ('is_Employee', models.BooleanField(default=False)),
                ('is_HR', models.BooleanField(default=False)),
                ('is_Manager', models.BooleanField(default=False)),
                ('is_Owner', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OwnerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FullName', models.CharField(max_length=250)),
                ('Experience', models.CharField(max_length=600)),
                ('skills', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), default=list, size=None)),
                ('Projects_Completed', models.IntegerField(default='10+')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='owner_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='NewJoineProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('FullName', models.CharField(max_length=250)),
                ('Resume', models.FileField(upload_to='Profile/Resumes/')),
                ('AdharCard', models.ImageField(upload_to='Profile/Adhar/')),
                ('technology', models.CharField(blank=True, max_length=100, null=True)),
                ('Experience', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='newjoine_profiles', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ManagerProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('FullName', models.CharField(max_length=250)),
                ('department', models.CharField(max_length=100)),
                ('Team', models.CharField(default='Pending', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='manager_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='InternProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('FullName', models.CharField(max_length=250)),
                ('skills', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), default=list, size=None)),
                ('Task', models.CharField(max_length=200, null=True)),
                ('Assigner', models.CharField(choices=[('MG', 'Manager'), ('EP', 'Employee'), ('OWN', 'Owner'), ('HR', 'HR')], max_length=60)),
                ('next_Intrest', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), default=list, size=None)),
                ('Part_of_Project', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='intern_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HrProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('FullName', models.CharField(max_length=250)),
                ('department', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=100)),
                ('contact_number', models.CharField(max_length=15, unique=True)),
                ('candidates_managed', models.PositiveIntegerField(default=0)),
                ('employees_under', models.PositiveIntegerField(default=0)),
                ('interviews_scheduled', models.PositiveIntegerField(default=0)),
                ('can_hire', models.BooleanField(default=True)),
                ('max_open_positions', models.IntegerField(default=1)),
                ('current_openings', models.IntegerField(default=0)),
                ('can_assign_to_manager', models.BooleanField(default=True)),
                ('can_approve_leave', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hr_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('phone', models.CharField(blank=True, max_length=25, null=True)),
                ('Bio', models.FileField(default='PENDING', upload_to='Profile/BioFile')),
                ('Project', models.CharField(max_length=90)),
                ('Project_AssignedDate', models.DateTimeField()),
                ('Assigner', models.CharField(choices=[('MG', 'Manager'), ('EP', 'Employee'), ('OWN', 'Owner'), ('HR', 'HR')], max_length=60)),
                ('TeamMembers', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), default=list, size=None)),
                ('skills', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), default=list, size=None)),
                ('PreviousCompany', models.FileField(default='Null', upload_to='Profile/PreCom/')),
                ('DayUpdate', models.CharField(default='PENDING', max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employee_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
