# Generated by Django 5.2.7 on 2025-12-03 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0002_managerprofile_profilepic'),
    ]

    operations = [
        migrations.AddField(
            model_name='newjoineprofile',
            name='skill',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
